#draw indian flag
import turtle
turtle.title("Indian Flag")
def rectangle(color):
    tur.begin_fill()
    for i in range(2):
        tur.fillcolor(color)
        tur.fd(200)
        tur.right(90)
        tur.fd(50)
        tur.right(90)
tur=turtle.Turtle()
tur.speed(0)
tur.up()
tur.goto(0,-200)
tur.down()
tur.goto(0,300)
rectangle("orange")
tur.end_fill()
tur.right(90)
tur.up()
tur.fd(50)
tur.left(90)

def rectangle2():
    for i in range(2):
        tur.fd(200)
        tur.down()
        tur.right(90)
        tur.fd(50)
        tur.right(90)
rectangle2()        
tur.right(90)
tur.up()
tur.fd(50)
tur.left(90)
def rectangle3(color):
    tur.begin_fill()
    tur.fillcolor(color)
    for i in range(2):
        
        tur.fd(200)
        tur.down()
        tur.right(90)
        tur.fd(50)
        tur.right(90)
rectangle3("green")  
tur.end_fill()              
tur.up()
tur.fd(100)
tur.down()
tur.circle(25)
tur.setheading(90)
tur.fd(50)
tur.setheading(360)
tur.right(90)
tur.up()
tur.fd(25)
tur.right(90)
tur.up()
tur.fd(25)
tur.right(180)
tur.down()
tur.fd(50)
tur.up()
tur.right(100)
tur.fd(18)
tur.right(120)
tur.down()
tur.fd(53)
tur.up()
tur.left(130)
tur.fd(32)

tur.left(130)
tur.down()
tur.fd(50)
tur.hideturtle()
